apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  namespace: "{{ project_name }}"
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
      - name: webserver
        image: "{{ docker_repo }}/{{ docker_image_path }}/{{ project_name }}:latest"
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        resources: {}
      dnsPolicy: ClusterFirst
      tolerations:
        - key: os
          value: Windows