---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ project_name }}"
  annotations:
    openshift.io/description: "{{ project_description }}"
    openshift.io/display-name: "{{ project_displayname }}"
  

