kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: webserver
  namespace: "{{ project_name }}"
  labels:
    app: webserver
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: webserver
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
